- name: Connectivity Test
  hosts: all
  tasks:
  - name: Ping
    ping: ~
  - name: Install nginx
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - python3-pip
    - libssl-dev
  - name: start nginx
    service:
      name: nginx
      state: started
